### ISSUE TITLE
A few other object-based SLAM-adjacent works

### ISSUE THREAD

**Issue by keevindoherty** [520xyxyzq/awesome-object-SLAM#4]
There are a few other papers you might consider adding to this great repository :)

In [our work on DC-SAM](https://arxiv.org/pdf/2204.11936.pdf) [RA-L '22] we consider MAP inference in hybrid graphical models with application to object-based SLAM. It is a more general library, but would be useful to practitioners interested in implementing object-based mapping/localization. Lots of potential there.

There are also a couple relevant review papers, most recently [Rosen et al. 2021](https://arxiv.org/abs/2103.05041) and [Garg et al. 2020](https://arxiv.org/abs/2101.00443), which it might be worthwhile to highlight for folks looking for a broader overview.

**Comment by 520xyxyzq** [comment]
Done! Thank you Kevin!
